_core:
  default_config_hash: gbxsfZiC2MMjzyiqbCPrKXXxlhQDa0pMNs0FSt_33ds
langcode: pt-br
enable: true
address: diego@vissini.com.br
roles: {  }
allowed: ''
description: true
message: true
mailkeys: ''
mailkeys_skip: ''
