_core:
  default_config_hash: rpfRQVoEn2ZWd_lw-iULKPiuina5CqcmzXWlz1OjTwM
langcode: pt-br
name: Faros
mail: faros@ielsc.org.br
simple_address: false
sitestyle: true
textonly: false
linkonly: false
user_plaintext_field: ''
format: full_html
preserve_class: false
advanced:
  incoming: false
  key: JCcdt84MEAVzSy0YJSk0-Qru8tHTgEW-wlUNp5hAmPI
